#!/usr/bin/env python3
"""
Autonomous Multi-Agent Orchestrator with AI-to-AI Automated Input
Coordinates planning, coordinate calculation, safety validation, content generation, and execution.
Enables "Zero-Manual-Typing" automation by generating text/code with a sub-agent.
"""

import json
import os
import sys
import time

# Resolve sys.path for absolute imports
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
GENRE_DIR = os.path.dirname(os.path.dirname(BASE_DIR))
sys.path.append(os.path.join(GENRE_DIR, "AI"))

from agent_harness import AgentHarness


class VisionAgent:
    """Specialized Agent for OpenCV template alignment and visual state retrieval."""
    def __init__(self, harness: AgentHarness):
        self.harness = harness

    def execute_calibration(self):
        print("🤖 [VisionAgent] Running template calibration...")
        # Simulate finding the reference marker at (150, 120) instead of expected (100, 100)
        self.harness.offset_x = 50
        self.harness.offset_y = 20
        print(f"🤖 [VisionAgent] Calibration complete. Found offset: X={self.harness.offset_x}px, Y={self.harness.offset_y}px")
        return {"offset_x": self.harness.offset_x, "offset_y": self.harness.offset_y}


class ContentAgent:
    """Specialized Agent representing 'another AI' that generates text/code to type into input boxes."""
    def generate_content(self, context_prompt):
        print(f"🤖 [ContentAgent] Generating content based on context: '{context_prompt}'")
        # Simulating dynamic text generation based on what the planner needs
        if "検索" in context_prompt:
            generated_text = "Slay the Spire 2 release notes 2026"
        elif "フィードバック" in context_prompt or "報告" in context_prompt:
            generated_text = "システムは正常に動作しています。自動キャリブレーションに成功しました。"
        else:
            generated_text = "自動処理を実行中..."
        print(f"🤖 [ContentAgent] Drafted input text: '{generated_text}'")
        return generated_text


class PlannerAgent:
    """Specialized Agent representing the Gemma Brain that decides click targets and actions."""
    def __init__(self, harness: AgentHarness):
        self.harness = harness

    def select_action(self, iteration, error_history):
        print(f"🤖 [PlannerAgent] Deciding next action based on goal and error history...")
        if error_history:
            print(f"🤖 [PlannerAgent] Reading failure history to self-correct: {error_history[-1]}")

        # Simulate dynamic self-healing decisions involving clicking and typing
        if iteration == 1:
            # First attempt: Selects an unsafe coordinate
            return {
                "action": "click",
                "target_x": 1250,
                "target_y": 700,
                "reason": "Dangerous zone button click attempt"
            }
        elif iteration == 2:
            # Second attempt: Click on a search input box (safe coord) to focus it
            return {
                "action": "click",
                "target_x": 400,
                "target_y": 150,
                "reason": "Click search input box to focus"
            }
        elif iteration == 3:
            # Third attempt: Type query into the focused box (automatically generated by ContentAgent)
            return {
                "action": "type",
                "target_x": 400,
                "target_y": 150,
                "input_context": "最新のゲームアップデート情報を検索するためのキーワード",
                "reason": "Type automatically generated query into search box"
            }
        elif iteration == 4:
            # Fourth attempt: Select a coordinate that fails state verification
            return {
                "action": "click",
                "target_x": 500,
                "target_y": 250,
                "reason": "Click update button attempt (simulates verification fail)"
            }
        elif iteration == 5:
            # Fifth attempt: Click on feedback text area and type status report (corrected)
            return {
                "action": "type",
                "target_x": 600,
                "target_y": 350,
                "input_context": "実行結果のステータス報告フィードバック",
                "reason": "Type automated status update to feedback area"
            }
        else:
            return {
                "action": "done",
                "target_x": 0,
                "target_y": 0,
                "reason": "Task completed successfully"
            }


class GuardAgent:
    """Specialized Agent enforcing fail-safe margin rules and target validation."""
    def __init__(self, harness: AgentHarness):
        self.harness = harness

    def validate_coordinates(self, tx, ty):
        print(f"🤖 [GuardAgent] Validating LLM targets: ({tx}, {ty}) with offsets (+{self.harness.offset_x}, +{self.harness.offset_y})")
        final_x = tx + self.harness.offset_x
        final_y = ty + self.harness.offset_y

        sw = self.harness.screen_width
        sh = self.harness.screen_height
        margin = self.harness.safety_margin

        # Boundary check
        if (final_x < margin or final_x > sw - margin or
                final_y < margin or final_y > sh - margin):
            print(f"⚠️ [GuardAgent] FAIL-SAFE TRIGGERED! Coordinate ({final_x}, {final_y}) violates safety margin {margin}px.")
            return {"valid": False, "final_x": final_x, "final_y": final_y, "reason": "Safety margin violation"}
        
        print(f"🤖 [GuardAgent] Coordinate ({final_x}, {final_y}) is safe and approved.")
        return {"valid": True, "final_x": final_x, "final_y": final_y}


class VerifyAgent:
    """Specialized Agent simulating screen state diff hashing and click/type verification."""
    def verify_action_state(self, action, tx, ty, val=""):
        print(f"🤖 [VerifyAgent] Verifying action '{action}' outcome for target ({tx}, {ty})...")
        if tx == 500 and ty == 250:
            # Simulate click verification failure (static state, no change detected)
            print("⚠️ [VerifyAgent] Verification FAILED: Screen hash is identical. No state transition.")
            return {"success": False, "error": "Action did not trigger any visual state change."}
        else:
            if action == "type":
                print(f"✅ [VerifyAgent] Verification SUCCESS: Text '{val}' entered and verified in input box.")
            else:
                print("✅ [VerifyAgent] Verification SUCCESS: Screen state transition confirmed.")
            return {"success": True}


class AutonomousOrchestrator:
    def __init__(self, safety_margin=100):
        self.harness = AgentHarness(safety_margin=safety_margin)
        self.harness.screen_width = 1280
        self.harness.screen_height = 720

        # Instantiate sub-agents
        self.vision_agent = VisionAgent(self.harness)
        self.planner_agent = PlannerAgent(self.harness)
        self.guard_agent = GuardAgent(self.harness)
        self.verify_agent = VerifyAgent()
        self.content_agent = ContentAgent()

        self.error_history = []

    def run_orchestrator(self, goal, max_cycles=7):
        print(f"==================================================")
        print(f"👑 [Orchestrator] Starting Multi-Agent Orchestration Loop")
        print(f"👑 [Orchestrator] Goal: {goal}")
        print(f"👑 [Orchestrator] Mode: Autopilot AI-to-AI Input (No Manual Entry)")
        print(f"==================================================")

        # 1. Delegate calibration to VisionAgent
        self.vision_agent.execute_calibration()

        cycle = 1
        while cycle <= max_cycles:
            print(f"\n--- [Orchestrator] Starting Cycle {cycle} ---")
            
            # 2. Query PlannerAgent for next action target
            action_data = self.planner_agent.select_action(cycle, self.error_history)
            action = action_data.get("action")
            reason = action_data.get("reason")
            
            if action == "done":
                print(f"\n👑 [Orchestrator] SUCCESS! Task completed. Final status: DONE.")
                self.print_report(goal)
                return True

            tx = action_data.get("target_x", 0)
            ty = action_data.get("target_y", 0)
            print(f"👑 [Orchestrator] Planner selected action '{action}' at target ({tx}, {ty}) because: '{reason}'")

            # 3. Delegate safety validation to GuardAgent
            guard_output = self.guard_agent.validate_coordinates(tx, ty)
            
            if not guard_output["valid"]:
                err_msg = f"GuardAgent blocked click at ({tx}, {ty}) -> final ({guard_output['final_x']}, {guard_output['final_y']}) due to boundary violation."
                print(f"👑 [Orchestrator] Action intercepted: {err_msg}")
                self.error_history.append(err_msg)
                cycle += 1
                continue

            final_x = guard_output["final_x"]
            final_y = guard_output["final_y"]

            # 4. Handle auto-typing via ContentAgent ("他のAIに書かせる/入力する")
            if action == "type":
                context_prompt = action_data.get("input_context", "一般入力")
                print(f"👑 [Orchestrator] Text input box detected. Querying ContentAgent to generate input content...")
                generated_text = self.content_agent.generate_content(context_prompt)
                
                print(f"👑 [Orchestrator] Automatically typing '{generated_text}' at coordinates ({final_x}, {final_y}) via harness...")
                # Execute simulated/physical typing
                self.harness.offset_x = 0  # temporarily clear offset since final_x already includes offset
                self.harness.offset_y = 0
                self.harness.execute_safe_action(final_x, final_y, action_type="type", input_text=generated_text)
                # Restore offsets
                self.harness.offset_x = 50
                self.harness.offset_y = 20

                # Verify typing state
                verify_output = self.verify_agent.verify_action_state("type", tx, ty, generated_text)
                
                # Feedback loop: simulate that the text box reacted precisely at target (since we already applied correction)
                corr_tx, corr_ty = self.harness.calibrator.apply_systematic_correction(tx, ty)
                self.harness.calibrator.record_click_feedback(tx, ty, corr_tx, corr_ty)
            else:
                print(f"👑 [Orchestrator] Executing click at physical coordinates ({final_x}, {final_y})...")
                # Execute simulated/physical click
                self.harness.offset_x = 0
                self.harness.offset_y = 0
                self.harness.execute_safe_action(final_x, final_y, action_type="click")
                self.harness.offset_x = 50
                self.harness.offset_y = 20

                verify_output = self.verify_agent.verify_action_state("click", tx, ty)
                
                # Feedback loop: If we clicked the search input box at (400, 150) for the first time,
                # simulate that the screen actually responded at (405, 147) (an offset error / 習性誤差).
                if tx == 400 and ty == 150 and len(self.harness.calibrator.click_history) == 0:
                    print("🔍 [Orchestrator-Vision] Visual state diff detected! Input box activated at (405, 147) instead of target (400, 150). Logging error delta (習性誤差)...")
                    self.harness.calibrator.record_click_feedback(tx, ty, 405, 147)
                else:
                    # Otherwise, simulate perfect target response based on current calibration
                    corr_tx, corr_ty = self.harness.calibrator.apply_systematic_correction(tx, ty)
                    self.harness.calibrator.record_click_feedback(tx, ty, corr_tx, corr_ty)

            # 5. Handle action verification
            if not verify_output["success"]:
                err_msg = f"VerifyAgent reported failure at ({tx}, {ty}) -> final ({final_x}, {final_y}): {verify_output.get('error')}"
                print(f"👑 [Orchestrator] Action failed verification: {err_msg}")
                self.error_history.append(err_msg)
                cycle += 1
                continue

            print("👑 [Orchestrator] Cycle completed successfully. Proceeding...")
            cycle += 1

        print(f"\n👑 [Orchestrator] FAILED! Reached maximum cycle limit {max_cycles}.")
        return False

    def print_report(self, goal):
        print(f"\n==================================================")
        print(f"📝 [Orchestrator] AUTONOMOUS RUN REPORT")
        print(f"==================================================")
        print(f"Target Goal: {goal}")
        print(f"Total Execution Cycles: {len(self.error_history) + 3}") # approximate successful cycles count
        print(f"Self-Corrected Errors encountered:")
        for idx, err in enumerate(self.error_history):
            print(f"  {idx + 1}. {err}")
        print(f"Final Status: SUCCESSFUL (No Manual Box Writing)")
        print(f"==================================================")


if __name__ == "__main__":
    orchestrator = AutonomousOrchestrator()
    orchestrator.run_orchestrator("自動で検索ボックスに入力し、ステータスを他のAIに書かせて送信する")
